name: '王者营地 Auto Get Points'

on:
  workflow_dispatch:
  push:
    branches: 
      - main
  schedule:
    - cron: '51 1 * * *'

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: python -m pip install --upgrade requests pyaes
    - name: 'Get points'
      env:
        WZRY_h5sign: ${{ secrets.WZRY_h5sign }}
      run: python3 wzry.py
